export const CONFIG_SUCURSAL = {

  SUCURSAL: "MONTEMORELOS",
  RUTA_TRANSFERENCIAS: "SOLTRAN",

  TITULO_APP: "SOLICITUD DE TRANSFERENCIA",
  TITULO_NAVEGADOR: "SOLICITUD MERCANCIA MATRIZ",
  SUCURSAL_HEADER: "MONTEMORELOS",

  LOGO: "logo.jfif",

  PREFIJO_FOLIO: "MON",

  FIREBASE: {
    RAIZ_TIENDAS: "TIENDAS",
    SUCURSAL: "MONTEMORELOS",
    COLECCION_TRANSFERENCIAS: "SOLTRAN",
    COLECCION_FOTOS_META: "productos_fotos_meta",
    COLECCION_PRODUCTOS: "productos"
  },

  INDEXEDDB: {
    DB_NAME: "PROVSOFT_PDD_MOVIL",
    DB_VERSION: 3,
    STORE_PRODUCTOS: "catalogo_productos_completo",
    STORE_META: "metadata",
    STORE_FOTOS_META: "fotos_productos_meta",
    STORE_BORRADOR: "borrador_transferencia"
  },

  CLAVES: {
    ULTIMA_DESCARGA_CATALOGO: "ultima_descarga_catalogo",
    BORRADOR: "borrador_actual"
  },

  HORAS_ENTRE_DESCARGAS: 48

};
