import { cargarProveedoresAutorizados, cargarEquivalencias, guardarEquivalencia, cargarProductosActivosLocal, sincronizarProductosActivosLocal, filtrarProductosCatalogo } from './configuracion.js';
import { cargarFacturasOrigen, filtrarFacturasPendientesParaZapata } from './facturas.js';
import { prepararArticulosEntrada, generarEntradaZapata } from './entradas.js';

let proveedores=[]; let equivalencias=[]; let facturas=[]; let factura=null; let articulos=[]; let productos=[]; let productosListos=false; let indiceArticulo=null; let productoElegido=null; let scannerStream=null; let scannerTimer=null; let facingMode='environment';
const $=id=>document.getElementById(id);

document.addEventListener('DOMContentLoaded',()=>{configurar(); cargarTodo();});
function configurar(){
  $('btnRefrescar').onclick=()=>cargarTodo(true); $('buscarFactura').oninput=pintarFacturas;
  $('btnVolver').onclick=()=>mostrarVista('vistaFacturas'); $('btnVolverFactura').onclick=()=>{mostrarVista('vistaFactura'); cerrarScanner();};
  $('btnAutorizarEntrada').onclick=autorizarEntrada; $('buscarProducto').oninput=debounce(buscarProducto,100); $('btnLimpiarBusqueda').onclick=()=>{$('buscarProducto').value='';buscarProducto();$('buscarProducto').focus();};
  $('btnCamara').onclick=abrirScanner; $('btnCerrarScanner').onclick=cerrarScanner; $('btnCambiarCamara').onclick=async()=>{facingMode=facingMode==='environment'?'user':'environment'; await iniciarCamara();};
  $('btnBuscarCodigoFactura').onclick=()=>{const a=articulos[indiceArticulo]; $('buscarProducto').value=a?.codigo_factura||''; buscarProducto();};
  $('cantidadEntrada').oninput=syncFactor; $('factorConversion').oninput=syncCantidad; $('btnGuardarEnlace').onclick=guardarEnlace;
}
async function cargarTodo(mostrar=true){
  if(mostrar) loading('Actualizando facturas…');
  try{
    proveedores=await cargarProveedoresAutorizados();
    equivalencias=await cargarEquivalencias();
    const rfcs=proveedores.filter(p=>p.activo).map(p=>p.rfc_emisor);
    const origen=await cargarFacturasOrigen(1000,rfcs);
    facturas=await filtrarFacturasPendientesParaZapata(origen,proveedores);
    pintarFacturas();
  }catch(e){toast(e.message||'No se pudieron cargar las facturas','error');}
  finally{ocultarLoading();}
}
function pintarFacturas(){
  const q=normalizar($('buscarFactura').value); const lista=q?facturas.filter(f=>normalizar(`${f.razon_social_emisor||''} ${f.rfc_emisor||''} ${f.serie||''} ${f.folio||''} ${f.uuid_cfdi||f.id||''}`).includes(q)):facturas;
  $('contadorFacturas').textContent=lista.length; const box=$('listaFacturas');
  if(!lista.length){box.innerHTML='<div class="empty">No hay facturas pendientes con ese filtro.</div>';return;}
  box.innerHTML=lista.map(f=>{const idx=facturas.indexOf(f); const arts=prepararArticulosEntrada(f,equivalencias); const total=arts.length; const enlazados=arts.filter(a=>a.equivalencia_encontrada).length; const pct=total?Math.round(enlazados*100/total):0; const estado=pct===100?'completo':pct>0?'proceso':'sin-iniciar'; const texto=pct===100?'Lista para entrada':pct>0?'En proceso':'Sin iniciar'; return `<article class="invoice-card"><div class="invoice-top"><h3>${esc(f.razon_social_emisor||f.rfc_emisor||'Proveedor')}</h3><span class="percent-badge ${estado}">${pct}%</span></div><div class="meta"><span>Folio ${esc([f.serie,f.folio].filter(Boolean).join('-')||'—')}</span><span>${esc(fecha(f))}</span></div><div class="link-summary"><div><b>${enlazados} de ${total}</b> artículos enlazados</div><span class="status-text ${estado}">${texto}</span></div><div class="progress-track"><div class="progress-fill ${estado}" style="width:${pct}%"></div></div><div class="row"><div><div class="subtle">Total factura</div><div class="money">${moneda(f.total)}</div></div><button class="primary abrir" data-i="${idx}">${pct===100?'Revisar':'Continuar'} →</button></div></article>`}).join('');
  box.querySelectorAll('.abrir').forEach(b=>b.onclick=()=>abrirFactura(Number(b.dataset.i)));
}
function abrirFactura(i){factura=facturas[i]; articulos=prepararArticulosEntrada(factura,equivalencias); pintarFactura(); mostrarVista('vistaFactura'); window.scrollTo(0,0);}
function pintarFactura(){
  const enlazados=articulos.filter(a=>a.equivalencia_encontrada).length; $('progresoFactura').textContent=`${enlazados} / ${articulos.length}`;
  $('cabeceraFactura').innerHTML=`<h2>${esc(factura?.razon_social_emisor||'Factura')}</h2><div class="subtle">${esc(factura?.rfc_emisor||'')} · Folio ${esc([factura?.serie,factura?.folio].filter(Boolean).join('-')||'—')} · ${esc(fecha(factura))}</div>`;
  $('listaArticulos').innerHTML=articulos.map((a,i)=>`<article class="article-card ${a.equivalencia_encontrada?'linked':'pending'}"><div class="article-title">${esc(a.descripcion_factura||'Sin descripción')}</div><div class="article-code">${esc(a.codigo_factura||'SIN CÓDIGO')}</div><div class="article-meta"><span class="chip">Factura: ${num(a.cantidad_factura)} ${esc(a.unidad_factura||'')}</span>${a.equivalencia_encontrada?`<span class="chip ok">✓ Enlazado</span><span class="chip">${esc(a.codigo_interno)} · ${esc(a.descripcion_interna)}</span><span class="chip">Entra: ${num(a.cantidad_entrada)}</span>`:'<span class="chip warn">Pendiente de enlace</span>'}</div><div class="article-action"><button class="${a.equivalencia_encontrada?'secondary':'primary'} enlazar" data-i="${i}">${a.equivalencia_encontrada?'Cambiar enlace':'📦 Buscar en piso y enlazar'}</button></div></article>`).join('');
  $('listaArticulos').querySelectorAll('.enlazar').forEach(b=>b.onclick=()=>abrirEnlace(Number(b.dataset.i)));
  $('btnAutorizarEntrada').disabled=!articulos.length||articulos.some(a=>!a.equivalencia_encontrada);
}
async function abrirEnlace(i){indiceArticulo=i; productoElegido=null; const a=articulos[i]; $('conceptoActual').innerHTML=`<div class="desc">${esc(a.descripcion_factura)}</div><div class="code">Código factura: <b>${esc(a.codigo_factura||'SIN CÓDIGO')}</b></div><div class="article-meta"><span class="chip">Cantidad: ${num(a.cantidad_factura)} ${esc(a.unidad_factura||'')}</span></div>`; $('productoElegido').classList.add('oculto'); $('conversionBox').classList.add('oculto'); $('buscarProducto').value=''; mostrarVista('vistaEnlace'); window.scrollTo(0,0); await asegurarProductos(); $('buscarProducto').value=a.codigo_factura||a.descripcion_factura||''; buscarProducto();}
async function asegurarProductos(){if(productosListos)return; loading('Preparando catálogo de productos…'); try{productos=await cargarProductosActivosLocal(); if(!productos.length)productos=await sincronizarProductosActivosLocal(); productosListos=true;}catch(e){toast(e.message||'No se pudo cargar el catálogo','error');}finally{ocultarLoading();}}
function buscarProducto(){const q=$('buscarProducto').value; const res=filtrarProductosCatalogo(productos,q); const box=$('listaProductos'); if(!res.length){box.innerHTML='<div class="empty">Sin coincidencias. Prueba otro código o descripción.</div>';return;} box.innerHTML=res.slice(0,40).map((p,i)=>`<div class="product"><div><b>${esc(p.codigoBarra||p.id||'')}</b><span>${esc(p.concepto||'')}</span><small>${esc([p.marca,p.departamento].filter(Boolean).join(' · '))}</small></div><button data-i="${i}">Elegir</button></div>`).join(''); box.querySelectorAll('button').forEach(b=>b.onclick=()=>elegirProducto(res[Number(b.dataset.i)]));}
function elegirProducto(p){productoElegido=p; const a=articulos[indiceArticulo]; const factor=Number(a.factor_conversion||1); $('productoElegido').innerHTML=`<h3>${esc(p.concepto||'Producto')}</h3><div class="article-code">${esc(p.codigoBarra||p.id||'')}</div>`; $('productoElegido').classList.remove('oculto'); $('cantidadFactura').value=numInput(a.cantidad_factura); $('cantidadEntrada').value=numInput(Number(a.cantidad_factura||0)*factor); $('factorConversion').value=numInput(factor); $('conversionBox').classList.remove('oculto'); $('listaProductos').innerHTML='';}
function syncFactor(){const cf=Number($('cantidadFactura').value||0), ce=Number($('cantidadEntrada').value||0); if(cf>0)$('factorConversion').value=numInput(ce/cf);}
function syncCantidad(){const cf=Number($('cantidadFactura').value||0), factor=Number($('factorConversion').value||1); $('cantidadEntrada').value=numInput(cf*factor);}
async function guardarEnlace(){const a=articulos[indiceArticulo]; if(!a||!productoElegido)return toast('Selecciona un producto','error'); const ce=Number($('cantidadEntrada').value||0); if(!(ce>0))return toast('La cantidad de entrada debe ser mayor a cero','error'); const cf=Number(a.cantidad_factura||0); const factor=cf>0?ce/cf:Number($('factorConversion').value||1); loading('Guardando equivalencia…'); try{await guardarEquivalencia({texto_factura:`${a.codigo_factura||''} ${a.descripcion_factura||''}`.trim(),codigo_interno:String(productoElegido.codigoBarra||productoElegido.id||''),descripcion_interna:String(productoElegido.concepto||''),unidad_factura:a.unidad_factura||'',unidad_inventario:productoElegido.unidadMedidaSat||'',factor_conversion:factor}); equivalencias=await cargarEquivalencias(); articulos=prepararArticulosEntrada(factura,equivalencias); pintarFactura(); mostrarVista('vistaFactura'); toast('Equivalencia guardada','ok'); const siguiente=articulos.findIndex((x,idx)=>idx>indiceArticulo&&!x.equivalencia_encontrada); if(siguiente>=0)setTimeout(()=>abrirEnlace(siguiente),450);}catch(e){toast(e.message||'No se pudo guardar','error');}finally{ocultarLoading();}}
async function autorizarEntrada(){if(!factura||articulos.some(a=>!a.equivalencia_encontrada))return; if(!confirm('¿Autorizar la entrada de esta factura?'))return; loading('Generando entrada…'); try{await generarEntradaZapata(factura,articulos,'MOVIL_PISO'); toast('Entrada autorizada y guardada','ok'); await cargarTodo(false); mostrarVista('vistaFacturas');}catch(e){toast(e.message||'No se pudo generar la entrada','error');}finally{ocultarLoading();}}
async function abrirScanner(){if(!('mediaDevices'in navigator))return toast('Este navegador no permite cámara','error'); $('scannerModal').classList.remove('oculto'); await iniciarCamara();}
async function iniciarCamara(){cerrarStream(); $('scannerStatus').textContent='Iniciando cámara…'; try{scannerStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facingMode},width:{ideal:1280},height:{ideal:720}},audio:false}); $('scannerVideo').srcObject=scannerStream; await $('scannerVideo').play(); $('scannerStatus').textContent='Apunta al código de barras.'; iniciarDeteccion();}catch(e){$('scannerStatus').textContent='No se pudo abrir la cámara. Revisa el permiso.'; toast('Permiso de cámara no disponible','error');}}
function iniciarDeteccion(){clearInterval(scannerTimer); if(!('BarcodeDetector'in window)){ $('scannerStatus').textContent='Tu navegador no trae lector automático. Puedes usar la búsqueda manual.'; return;} let detector; try{detector=new BarcodeDetector({formats:['ean_13','ean_8','upc_a','upc_e','code_128','code_39','itf']});}catch{detector=new BarcodeDetector();} scannerTimer=setInterval(async()=>{try{if($('scannerVideo').readyState<2)return; const codes=await detector.detect($('scannerVideo')); if(codes?.length){const code=codes[0].rawValue||''; if(code){$('buscarProducto').value=code; cerrarScanner(); buscarProducto(); toast(`Código leído: ${code}`);}}}catch{}},450);}
function cerrarScanner(){$('scannerModal').classList.add('oculto'); cerrarStream();}
function cerrarStream(){clearInterval(scannerTimer); scannerTimer=null; if(scannerStream){scannerStream.getTracks().forEach(t=>t.stop());scannerStream=null;} $('scannerVideo').srcObject=null;}
function mostrarVista(id){document.querySelectorAll('.vista').forEach(v=>v.classList.remove('activa'));$(id).classList.add('activa');}
function loading(t){$('loadingText').textContent=t||'Cargando…';$('loading').classList.remove('oculto')}function ocultarLoading(){$('loading').classList.add('oculto')}
let toastTimer; function toast(t,tipo=''){clearTimeout(toastTimer);$('toast').textContent=t;$('toast').className=`toast ${tipo}`;toastTimer=setTimeout(()=>$('toast').classList.add('oculto'),2400)}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))} function normalizar(s){return String(s||'').toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Z0-9]+/g,' ').trim()} function fecha(f){const x=f?.fecha_factura||f?.fecha||f?.fecha_emision||''; return String(x).slice(0,10)||'—'} function moneda(n){return new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(n||0))} function num(n){return new Intl.NumberFormat('es-MX',{maximumFractionDigits:4}).format(Number(n||0))} function numInput(n){const x=Number(n||0);return Number.isFinite(x)?String(Math.round(x*1000000)/1000000):'0'} function debounce(fn,ms){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}}
