export const CONFIG_SUCURSAL = {

  SUCURSAL: "CENTRAL",
  RUTA_TRANSFERENCIAS: "SOLTRAN",

  TITULO_APP: "SOLICITUD DE TRANSFERENCIA",
  TITULO_NAVEGADOR: "Transferencia Solicitud - PROVSOFT",
  SUCURSAL_HEADER: "SUCURSAL CENTRAL",

  LOGO: "logo.jfif",

  PREFIJO_FOLIO: "SOL",

  FIREBASE: {
    RAIZ_TIENDAS: "TIENDAS",
    SUCURSAL: "CENTRAL",
    COLECCION_TRANSFERENCIAS: "SOLTRAN",
    COLECCION_PRODUCTOS: "productos",
    COLECCION_FOTOS_META: "productos_fotos_meta"
  },

  INDEXEDDB: {
    DB_NAME: "PROVSOFT_PDD_MOVIL",
    DB_VERSION: 3,
    STORE_PRODUCTOS: "catalogo_productos_completo",
    STORE_META: "metadata"
  },

  CLAVES: {
    ULTIMA_DESCARGA_CATALOGO: "ultima_descarga_catalogo"
  },

  HORAS_ENTRE_DESCARGAS: 48

};
