plugins {
    id 'com.android.application'
}

android {
    namespace 'mx.proveedora.salidapdd'
    compileSdk 35

    defaultConfig {
        applicationId 'mx.proveedora.salidapdd'
        minSdk 23
        targetSdk 35
        versionCode 46
        versionName '4.6'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.12.1'
    implementation 'androidx.core:core:1.15.0'
}
