export const CONFIG_SUCURSAL = {

  SUCURSAL: "RIOVERDE",
  SUCURSAL_FIREBASE: "RIO VERDE",

  RUTA_TRANSFERENCIAS: "SOLTRAN",

  TITULO_APP: "SOLICITUD DE TRANSFERENCIA",
  TITULO_NAVEGADOR: "Transferencia Solicitud Rio Verde - PROVSOFT",
  SUCURSAL_HEADER: "RIO VERDE",

  LOGO: "logo.jfif",

  PREFIJO_FOLIO: "RIOTRANSF",
  ZONA: "ZONA1",

  FIREBASE: {
    RAIZ_TIENDAS: "TIENDAS",
    SUCURSAL: "RIO VERDE",
    COLECCION_TRANSFERENCIAS: "SOLTRAN",
    COLECCION_PRODUCTOS: "productos",
    COLECCION_FOTOS_META: "productos_fotos_meta"
  },

  INDEXEDDB: {
    DB_NAME: "PROVSOFT_PDD_MOVIL",
    DB_VERSION: 2,
    STORE_PRODUCTOS: "catalogo_productos_completo",
    STORE_META: "metadata"
  },

  CLAVES: {
    ULTIMA_DESCARGA_CATALOGO: "ultima_descarga_catalogo"
  },

  HORAS_ENTRE_DESCARGAS: 48

};
